language: python
python:
  - "2.7"
before_install:
  - sudo sh -c "echo deb http://www.openfoam.org/download/ubuntu precise main > /etc/apt/sources.list.d/openfoam.list"
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes openfoam222
  - sudo apt-get install libhdf5-serial-dev
  - chmod +x ./install_pyFoam.sh
  - sudo ./install_pyFoam.sh
  # (1) Install cython and numexpr externally because the requirements does
  #     not work with them
  # (2) Pytables breaks with latest Cython
  #     see https://github.com/PyTables/PyTables/issues/388
  - pip install numexpr cython==0.20
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt
  - pip install -r doc_requirements.txt
  - pip install coveralls
install:
  - python setup.py develop
script:
  - coverage run -m unittest discover
  - flake8 . --exclude= PyFoam/*
after_success:
  - coveralls
