""" Provisional CUBA keywords specific for this revision

"""

from enum import IntEnum, unique


@unique
class CUBAExt(IntEnum):

    INCOMPRESSIBLE = 1
    COMPRESSIBLE = 2
    VOF_MODEL = 3
    LAMINAR_MODEL = 4
    GE = 5
    PATCH_TYPE = 6
    PHASE_LIST = 7
    MAX_COURANT_NUMBER = 8
    SURFACE_TENSION = 9
    NUMBER_OF_CORES = 10
    DYNAMIC_PRESSURE = 11
    FLUX = 12
    MIXTURE_MODEL = 13
    RELATIVE_VELOCITY_MODEL = 14
    RELATIVE_VELOCITY_MODEL_COEFFS = 15
    VISCOSITY_MODEL = 16
    VISCOSITY_MODEL_COEFFS = 17
    EXTERNAL_BODY_FORCE_MODEL = 18
    EXTERNAL_BODY_FORCE_MODEL_COEFFS = 19
    STRESS_MODEL = 20
