#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean libso mixtureViscosityModels
wclean libso relativeVelocityModels
wclean libso incompressibleTwoPhaseInteractingMixture
wclean

# ----------------------------------------------------------------- end-of-file
